controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    steering_controller:
      type: position_controllers/JointGroupPositionController

wheel_controller:
  ros__parameters:
    joints:
      - wheelRL_continuous
      - wheelRR_continuous
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

steering_controller:
  ros__parameters:
    joints:
      - wheelFC_steering_revolute
      # - wheelFR_steering_revolute
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
